/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pt_hokben;

import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
import pt_hokben.Session ;
/**
 *
 * @author Adm-004
 */
public class daftar_menu extends javax.swing.JFrame {

    /**
     * Creates new form homepemesan
     */
    private String nama ;
    public daftar_menu() {
        initComponents();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        slmt = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        daftar = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        slmt.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        slmt.setForeground(new java.awt.Color(0, 0, 0));
        slmt.setText("Selamat Datang");
        getContentPane().add(slmt);
        slmt.setBounds(210, 0, 110, 30);

        jLabel2.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Silahkan Pilih Menu");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(190, 30, 190, 20);

        daftar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No", "Nama Makanan", "Harga", "Title 4"
            }
        ));
        daftar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                daftarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(daftar);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 70, 453, 130);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(130, 0, 260, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Jakarta-Food-Delivery-Promotions.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 540, 300);

        setSize(new java.awt.Dimension(538, 332));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void daftarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_daftarMouseClicked
        // TODO add your handling code here:
        int baris            = daftar.rowAtPoint(evt.getPoint());
        String makanan       = daftar.getValueAt(baris,1).toString();
        String harga         = daftar.getValueAt(baris,2).toString();
        
        String[]  data = { makanan , harga  } ;
        this.dispose();
        form_pesan a = new form_pesan();
        a.setForm(data);
        a.setVisible(true);
        
    }//GEN-LAST:event_daftarMouseClicked

    /**
     * @param args the command line arguments
     */
    
    public void loadData(){
       DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("Nama Makanan");
        model.addColumn("Harga Makanan");
        model.addColumn("Opsi");
        
        //tampilkan data makanan kedalam table 
        try {
            int i =1 ;
            String sql = "Select * from master_makanan order by id_makanan asc " ;
            java.sql.Connection conn = (Connection)koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[] { i  ,  res.getString(2) , res.getString(4) , 
                 "Pilih" } );
                i++ ;
            }
            daftar.setModel(model);
        }catch(Exception e){
            
        } 
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(daftar_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(daftar_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(daftar_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(daftar_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new daftar_menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable daftar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel slmt;
    // End of variables declaration//GEN-END:variables
}
