/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pt_hokben;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import pt_hokben.Session;
/**
 *
 * @author Adm-004
 */
public class form_pesan extends javax.swing.JFrame {
private String name ;
    /**
     * Creates new form form_pesan
     */
    private String[] arr ; 
    public form_pesan() {
        initComponents();
        idPesanan();
        idTransaksi.setEnabled(false);
        nama.setText(Session.get_nama());
        nohp.setText(Session.get_nohp());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nohp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        makanan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamat = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        idTransaksi = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        hargamakan = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        qty = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Form Transaksi");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 10, 131, 31);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 150, 69, 40);

        nohp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nohpActionPerformed(evt);
            }
        });
        getContentPane().add(nohp);
        nohp.setBounds(200, 190, 180, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("No HP");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 180, 69, 40);

        makanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makananActionPerformed(evt);
            }
        });
        getContentPane().add(makanan);
        makanan.setBounds(200, 230, 180, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("Alamat");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 350, 66, 20);

        alamat.setColumns(20);
        alamat.setRows(5);
        jScrollPane1.setViewportView(alamat);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(200, 350, 250, 90);

        jButton1.setText("Pesan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(200, 450, 100, 40);

        jButton2.setText("Batalkan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(350, 450, 100, 40);

        idTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTransaksiActionPerformed(evt);
            }
        });
        getContentPane().add(idTransaksi);
        idTransaksi.setBounds(200, 110, 180, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("ID Pesanan");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 100, 69, 40);
        getContentPane().add(nama);
        nama.setBounds(200, 150, 180, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("Makanan di Pesan");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 220, 121, 40);

        hargamakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargamakanActionPerformed(evt);
            }
        });
        getContentPane().add(hargamakan);
        hargamakan.setBounds(200, 270, 180, 30);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setText("Harga Makanan");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(60, 260, 121, 40);

        qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyActionPerformed(evt);
            }
        });
        getContentPane().add(qty);
        qty.setBounds(200, 310, 180, 30);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel11.setText("QTY");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(60, 300, 121, 40);

        setSize(new java.awt.Dimension(571, 658));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nohpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nohpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nohpActionPerformed

    private void makananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_makananActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        daftar_menu a = new daftar_menu();
        a.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    public void idPesanan(){
        try {
            String sql  = "SELECT * FROM form_transaksi order by id_pesanan desc ";
            java.sql.Connection conn = (Connection)koneksi.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery(sql);
            
            if(rs.next()){
                String nofak = rs.getString("id_pesanan").substring(1);
                String AN    = "" + (Integer.parseInt(nofak) + 1 );
                String nol   = "" ;
                
                if(AN.length() == 1){
                    nol = "000" ;
                }else if(AN.length() == 2){
                    nol = "00" ;
                }else if(AN.length() == 3){
                    nol = "0" ;
                }else if(AN.length() == 4){
                    nol = "" ;
                }
                idTransaksi.setText("F" + nol + AN);
            }else {
                idTransaksi.setText("F0001");
            }
        
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    private  String getTanggal() {  
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");  
        Date date = new Date();  
        return dateFormat.format(date);  
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        form_pesan tgl = new form_pesan();
        String tanggal   = tgl.getTanggal() ;
        if(nama.getText().equals("")|| nohp.getText().equals("") ||
                makanan.getText().equals("") || hargamakan.getText().equals("") || alamat.getText().equals("")
                || qty.getText().equals("") ){
            JOptionPane.showMessageDialog(null,"field kosong");
        }else {
            try {
                String sql = "INSERT INTO  form_transaksi ("
                        + " id_pesanan , nama_penerima , nohp , "
                        + " nama_makanan , hrgmakanan ,alamat , status , tanggal , biayakirim , qty ) values "
                        + "('"+ idTransaksi.getText() +"' , '"+ nama.getText() +"' , '"+ nohp.getText() +"' ,"
                        + " '"+ makanan.getText() +"' , '"+ hargamakan.getText() +"' , '"+ alamat.getText() +"' ,"
                        + " 'Pending' , '"+ tanggal +"' , '"+ 0 +"' , "+ qty.getText() +"  ) " ;
                  java.sql.Connection conn = (Connection)koneksi.configDB();
                  java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                  pst.execute();
                  JOptionPane.showMessageDialog(null,"Pesanan di kirim harap tunggu");
                  this.dispose();
                  daftar_menu a = new daftar_menu();
                  a.setVisible(true);
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void idTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTransaksiActionPerformed

    private void hargamakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargamakanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargamakanActionPerformed

    private void qtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtyActionPerformed

    /**
     * @param args the command line arguments
     */
    public void setForm(String[] data){        
        makanan.setText(data[0]);
        makanan.setEnabled(false);
        hargamakan.setText(data[1]);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_pesan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_pesan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_pesan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_pesan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_pesan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamat;
    private javax.swing.JTextField hargamakan;
    private javax.swing.JTextField idTransaksi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField makanan;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nohp;
    private javax.swing.JTextField qty;
    // End of variables declaration//GEN-END:variables
}
