/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pt_hokben;

import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author E6530
 */
public class input_user extends javax.swing.JFrame {

    /**
     * Creates new form input_user
     */
    public input_user() {
        initComponents();
        idUser();
        id.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        bagian = new javax.swing.JTextField();
        nohp = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        cabang = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        password = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 295, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Input User");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(180, 20, 120, 22);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("ID User");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(57, 98, 40, 14);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Nama ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 150, 34, 14);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Bagian");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 230, 37, 14);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("No handpone");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 290, 69, 14);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("Email");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 350, 31, 14);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("cabang");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 400, 36, 14);
        getContentPane().add(id);
        id.setBounds(180, 90, 240, 25);
        getContentPane().add(nama);
        nama.setBounds(180, 140, 240, 26);
        getContentPane().add(bagian);
        bagian.setBounds(180, 230, 240, 29);
        getContentPane().add(nohp);
        nohp.setBounds(180, 280, 240, 28);
        getContentPane().add(email);
        email.setBounds(180, 340, 240, 28);
        getContentPane().add(cabang);
        cabang.setBounds(180, 400, 240, 28);

        save.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/diskette.png"))); // NOI18N
        save.setText("Simpan");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save);
        save.setBounds(180, 450, 110, 40);

        back.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/previous.png"))); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(330, 450, 80, 70);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setText("Password");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(60, 190, 80, 14);
        getContentPane().add(password);
        password.setBounds(180, 180, 240, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/fgg.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 570, 670);

        setSize(new java.awt.Dimension(536, 612));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public void reset(){
        id.setText("");
        nama.setText("");
        bagian.setText("");
        nohp.setText("");
        email.setText("");
        cabang.setText("");
        password.setText("");
        
    }
    
     public void idUser(){
        try {
            String sql  = "SELECT * FROM user order by iduser desc ";
            java.sql.Connection conn = (Connection)koneksi.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery(sql);
            
            if(rs.next()){
                String nofak = rs.getString("iduser").substring(1);
                String AN    = "" + (Integer.parseInt(nofak) + 1 );
                String nol   = "" ;
                
                if(AN.length() == 1){
                    nol = "000" ;
                }else if(AN.length() == 2){
                    nol = "00" ;
                }else if(AN.length() == 3){
                    nol = "0" ;
                }else if(AN.length() == 4){
                    nol = "" ;
                }
                id.setText("U" + nol + AN);
            }else {
                id.setText("U0001");
            }
        
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        if(id.getText().equals("") || nama.getText().equals("")|| bagian.getText().equals("") 
                || nohp.getText().equals("") || email.getText().equals("") || cabang.getText().equals("")){
            JOptionPane.showMessageDialog(null,"field kosong");
        }else {
            try {
                String sql = "INSERT INTO  user ("
                        + " iduser , nama , bagian , password , nohp , "
                        + " email , cabang ) values "
                        + "('"+ id.getText() +"' , '"+ nama.getText() +"' , '"+ bagian.getText() +"' , "
                        + " '"+ password.getText() +"' ,'"+ nohp.getText() +"' , '"+ email.getText() +"' , '"+ cabang.getText() +"' ) " ;
                  java.sql.Connection conn = (Connection)koneksi.configDB();
                  java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                  pst.execute();
                  JOptionPane.showMessageDialog(null,"Penyimpanan Berhasil");
                  reset();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e.getMessage());
            }
        }
        
    }//GEN-LAST:event_saveActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Master_user a  = new Master_user();
        a.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(input_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(input_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(input_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(input_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new input_user().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTextField bagian;
    private javax.swing.JTextField cabang;
    private javax.swing.JTextField email;
    private javax.swing.JTextField id;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nohp;
    private javax.swing.JTextField password;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
}
