/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pt_hokben;
import java.sql.Connection;
import javax.swing.JOptionPane;
import pt_hokben.koneksi;
/**
 *
 * @author E6530
 */
public class input_master_kendaraan extends javax.swing.JFrame {

    /**
     * Creates new form input_master_kendaraan
     */
    public input_master_kendaraan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        merk = new javax.swing.JTextField();
        jenis = new javax.swing.JTextField();
        nopolisi = new javax.swing.JTextField();
        masa = new javax.swing.JTextField();
        kondisi = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("ID Kendaraan");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(52, 90, 74, 14);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Merk Kendaraan");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(52, 131, 90, 14);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("No Polisi");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(52, 206, 48, 14);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Jenis Kendaraan");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(52, 170, 89, 14);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("Masa Kendaraan");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(52, 249, 89, 14);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("Kondisi Kendaraan");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(52, 293, 102, 14);
        getContentPane().add(id);
        id.setBounds(196, 84, 200, 30);
        getContentPane().add(merk);
        merk.setBounds(196, 127, 200, 30);
        getContentPane().add(jenis);
        jenis.setBounds(196, 166, 200, 30);
        getContentPane().add(nopolisi);
        nopolisi.setBounds(196, 202, 200, 30);
        getContentPane().add(masa);
        masa.setBounds(196, 245, 200, 30);
        getContentPane().add(kondisi);
        kondisi.setBounds(196, 289, 200, 30);

        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/diskette.png"))); // NOI18N
        save.setText("Simpan");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save);
        save.setBounds(200, 330, 100, 40);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Input Master Kendaraan");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(200, 10, 200, 22);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/previous.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(310, 330, 80, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/fgg.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 690, 750);

        setSize(new java.awt.Dimension(479, 475));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void reset(){
        id.setText("");
        merk.setText("");
        jenis.setText("");
        nopolisi.setText("");
        masa.setText("");
        kondisi.setText("");
    }
    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        if(id.getText().equals("") || merk.getText().equals("")|| jenis.getText().equals("") 
                || nopolisi.getText().equals("") || masa.getText().equals("") || kondisi.getText().equals("")){
            JOptionPane.showMessageDialog(null,"field kosong");
        }else {
            try {
                String sql = "INSERT INTO  master_kendaraan ("
                        + " kode_kendaraan , merk_kendaraan , jenis_kendaraan , "
                        + "no_polisi ,masa_kendaraan , kondisi_kendaraan ) values "
                        + "('"+ id.getText() +"' , '"+ merk.getText() +"' , '"+ jenis.getText() +"' , "
                        + "'"+ nopolisi.getText() +"' , '"+ masa.getText() +"' , '"+ kondisi.getText() +"' ) " ;
                  java.sql.Connection conn = (Connection)koneksi.configDB();
                  java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                  pst.execute();
                  JOptionPane.showMessageDialog(null,"Penyimpanan Berhasil");
                  reset();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e.getMessage());
            }
        }
    }//GEN-LAST:event_saveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Master_kendaraan a = new Master_kendaraan();
        a.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(input_master_kendaraan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(input_master_kendaraan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(input_master_kendaraan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(input_master_kendaraan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new input_master_kendaraan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jenis;
    private javax.swing.JTextField kondisi;
    private javax.swing.JTextField masa;
    private javax.swing.JTextField merk;
    private javax.swing.JTextField nopolisi;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
}
