/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pt_hokben;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Date;  
import java.text.DateFormat;  
import java.text.SimpleDateFormat;  
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import java.text.SimpleDateFormat;
/**
 *
 * @author dasep
 */
public class LaporanPendapatan extends javax.swing.JFrame {

     private String id ;
    /** Creates new form Laporan */
    public LaporanPendapatan() {
        initComponents();
        loadPesanan(this.id);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateComponentFormatter1 = new org.jdatepicker.impl.DateComponentFormatter();
        dateComponentFormatter2 = new org.jdatepicker.impl.DateComponentFormatter();
        dateComponentFormatter3 = new org.jdatepicker.impl.DateComponentFormatter();
        jDatePickerUtil1 = new org.jdatepicker.util.JDatePickerUtil();
        jDatePickerUtil2 = new org.jdatepicker.util.JDatePickerUtil();
        jDateComponentFactory1 = new org.jdatepicker.JDateComponentFactory();
        dateComponentFormatter4 = new org.jdatepicker.impl.DateComponentFormatter();
        jPanel1 = new javax.swing.JPanel();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        export = new javax.swing.JButton();
        pdf = new javax.swing.JButton();
        tanggal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        back.setText("Home");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("LAPORAN PENDAPATAN");

        export.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Microsoft_Excel-01_25074.png"))); // NOI18N
        export.setText("Export excel");
        export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportActionPerformed(evt);
            }
        });

        pdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/PDF_24287.png"))); // NOI18N
        pdf.setText("Export PDF");
        pdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdfActionPerformed(evt);
            }
        });

        jLabel2.setText("Masukan Tanggal");

        jButton1.setText("Date");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(export, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(pdf, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(export, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pdf, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(281, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(738, 499));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
         this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void exportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportActionPerformed
        // TODO add your handling code here:
        
        if(tanggal.getText().equals("")){
            JOptionPane.showMessageDialog(null,"input tanggal");
        }else {
            try {
                /*Nama file excell*/
                File theDir = new File("C:/BackupFile/");
                if (!theDir.exists()){
                    theDir.mkdirs();
                }
                String filename = "C:/BackupFile/LaporanPendapatan.xls" ;
                HSSFWorkbook workbook = new HSSFWorkbook();

                /*menentukan sheet*/
                HSSFSheet sheet = workbook.createSheet("Laporan Pendapatan");
                try {
                    String  sql = "select id_pesanan , tanggal ,nama_penerima ,nama_makanan , hrgmakanan , qty , total  "
                            + " from form_transaksi where tanggal= '"+ tanggal.getText() +"' and status = 'Sudah Sampai' " ;
                    String  sql2 = "select count(*) as jml  from form_transaksi"
                            + " where tanggal= '"+ tanggal.getText() +"' and status = 'Sudah Sampai' " ;

                    String  sql3 = "select sum(total) as pendapatan  from form_transaksi "
                            + "where tanggal= '"+ tanggal.getText() +"' and status = 'Sudah Sampai'" ;

                   // String sql2 = "Select count as total from form transaksi  where tanggal='"+ tanggal.getText() + "'" ;
                    int i =  1 ;
                    java.sql.Connection conn = (Connection)koneksi.configDB();
                    java.sql.Statement stm = conn.createStatement();
                    java.sql.ResultSet res = stm.executeQuery(sql);

                    java.sql.Statement stm2 = conn.createStatement();
                    java.sql.ResultSet res2 = stm2.executeQuery(sql2);

                    java.sql.Statement stm3 = conn.createStatement();
                    java.sql.ResultSet res3 = stm3.executeQuery(sql3);

                    res2.next();
                    res3.next();

                    if(res2.getString(1).equals("0")){
                         JOptionPane.showMessageDialog(null ,"tidak ada data");
                    }else {
                        HSSFRow rowhead = sheet.createRow((short)0);  /*index row 0*/
                        rowhead.createCell(0).setCellValue("ID Pesanan");  /*column 0*/
                        rowhead.createCell(1).setCellValue("Tanggal");  /*column 1*/
                        rowhead.createCell(2).setCellValue("Pemesan");  /*column 2*/
                        rowhead.createCell(3).setCellValue("Pesanan");  /*column 3*/
                        rowhead.createCell(4).setCellValue("Harga Makanan");  /*column 4*/
                        rowhead.createCell(5).setCellValue("QTY");  /*column 5*/
                        rowhead.createCell(6).setCellValue("Total");  /*column 6*/
                            while(res.next()){
                                HSSFRow row   = sheet.createRow((short)i);   /*index row 1*/
                                row.createCell(0).setCellValue(res.getString(1));  /*column 0*/
                                row.createCell(1).setCellValue(res.getString(2));  /* column  1*/
                                row.createCell(2).setCellValue(res.getString(3));  /* column 2*/
                                row.createCell(3).setCellValue(res.getString(4));  /* column 3*/
                                row.createCell(4).setCellValue(res.getString(5));  /* column 4*/
                                row.createCell(5).setCellValue(res.getString(6));  /* column 5*/
                                row.createCell(6).setCellValue(res.getString(7));  /* column 6*/
                                i++ ;
                            }
                                int a = Integer.parseInt(res2.getString(1));
                                HSSFRow rowFooter   = sheet.createRow((short) a + 1 );   /*index row 1*/
                                rowFooter.createCell(5).setCellValue("Total Pendapatan");  /* column 6*/
                                rowFooter.createCell(6).setCellValue(res3.getString(1));  /* column 6*/
                                FileOutputStream fileOut = new FileOutputStream(filename);
                                /*menulis file*/
                                workbook.write(fileOut);
                                /*menutup koneksi*/
                                fileOut.close();
                                JOptionPane.showMessageDialog(null, "Berhasil di export "  + filename);
                    }
                }catch(Exception e){
                    System.out.println(e);
                }
            } catch ( Exception ex ) {
                System.out.println(ex);
            }
        }
    }//GEN-LAST:event_exportActionPerformed

    private void pdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdfActionPerformed
        // TODO add your handling code here:
        try {
            String  sql = "select * from form_transaksi " ;
            java.sql.Connection conn = (Connection)koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            /* Step-2: Initialize PDF documents - logical objects */
        Document my_pdf_report = new Document();
        PdfWriter.getInstance(my_pdf_report, new FileOutputStream("C://TransaksiReport.pdf"));
        my_pdf_report.open();            
        my_pdf_report.add(new Paragraph("Laporan Transaksi",FontFactory.getFont(FontFactory.TIMES_BOLD, 18, Font.BOLD, BaseColor.BLUE)));
        my_pdf_report.add(new Paragraph(new Date().toString()));
        my_pdf_report.add(new Paragraph("-------------------------------------------------------------------"
                + "--------------------------------------------------------------"));
        my_pdf_report.add(new Paragraph("\n"));
        //we have four columns in our table
        PdfPTable my_report_table = new PdfPTable(9);
        //create a cell object
        PdfPCell table_cell;
        PdfPCell table_cell2;
        
        my_report_table.addCell("Kode Pesanan");
        my_report_table.addCell("Pemesan");
        my_report_table.addCell("No.Hp");
        my_report_table.addCell("Alamat");
        my_report_table.addCell("Makanan");
        my_report_table.addCell("Pengantar");
        my_report_table.addCell("Kendaraan");
        my_report_table.addCell("Tanggal");
        my_report_table.addCell("Total");
        my_report_table.setHeaderRows(1);
       
        while (res.next()) {                
            String id           = res.getString("id_pesanan");
            table_cell          = new PdfPCell(new Phrase(id));
            my_report_table.addCell(table_cell);
            
            String penerima        = res.getString("nama_penerima");
            table_cell          = new PdfPCell(new Phrase(penerima));
            my_report_table.addCell(table_cell);
            
            String nohp        = res.getString("nohp");
            table_cell          = new PdfPCell(new Phrase(nohp));
            my_report_table.addCell(table_cell);
            
            String alamat     = res.getString("alamat");
            table_cell          = new PdfPCell(new Phrase(alamat));
            my_report_table.addCell(table_cell);
            
            String makanan         = res.getString("nama_makanan");
            table_cell          = new PdfPCell(new Phrase(makanan));
            my_report_table.addCell(table_cell);
            
            String pengantar     = res.getString("nama_pengantar");
            table_cell=new PdfPCell(new Phrase(pengantar));
            my_report_table.addCell(table_cell);
            
            String kd     = res.getString("merk_kendaraan");
            table_cell=new PdfPCell(new Phrase(kd));
            my_report_table.addCell(table_cell);
            
            String tgl     = res.getString("tanggal");
            table_cell=new PdfPCell(new Phrase(tgl));
            my_report_table.addCell(table_cell);
            
            String total     = res.getString("total");
            table_cell=new PdfPCell(new Phrase(total));
            my_report_table.addCell(table_cell);
            
         }
        /* Attach report table to PDF */
        my_pdf_report.add(my_report_table);                       
        my_pdf_report.close();

        /* Close all DB related objects */
        JOptionPane.showMessageDialog(null,"Disimpan C://TransaksiReport.pdf");
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_pdfActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaporanPendapatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaporanPendapatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaporanPendapatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaporanPendapatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LaporanPendapatan().setVisible(true);
            }
        });
    }
    
    public void loadPesanan(String data){
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private org.jdatepicker.impl.DateComponentFormatter dateComponentFormatter1;
    private org.jdatepicker.impl.DateComponentFormatter dateComponentFormatter2;
    private org.jdatepicker.impl.DateComponentFormatter dateComponentFormatter3;
    private org.jdatepicker.impl.DateComponentFormatter dateComponentFormatter4;
    private javax.swing.JButton export;
    private javax.swing.JButton jButton1;
    private org.jdatepicker.JDateComponentFactory jDateComponentFactory1;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil1;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton pdf;
    private javax.swing.JTextField tanggal;
    // End of variables declaration//GEN-END:variables

}
