/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pt_hokben;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.DateFormat;  
import java.text.SimpleDateFormat;  
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
/**
 *
 * @author dasep
 */
public class LaporanPendapatan extends javax.swing.JFrame {

     private String id ;
    /** Creates new form Laporan */
    public LaporanPendapatan() {
        initComponents();
        loadPesanan(this.id);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateComponentFormatter1 = new org.jdatepicker.impl.DateComponentFormatter();
        dateComponentFormatter2 = new org.jdatepicker.impl.DateComponentFormatter();
        dateComponentFormatter3 = new org.jdatepicker.impl.DateComponentFormatter();
        jDatePickerUtil1 = new org.jdatepicker.util.JDatePickerUtil();
        jDatePickerUtil2 = new org.jdatepicker.util.JDatePickerUtil();
        jDateComponentFactory1 = new org.jdatepicker.JDateComponentFactory();
        dateComponentFormatter4 = new org.jdatepicker.impl.DateComponentFormatter();
        dateComponentFormatter5 = new org.jdatepicker.impl.DateComponentFormatter();
        jDateComponentFactory2 = new org.jdatepicker.JDateComponentFactory();
        jDatePickerUtil3 = new org.jdatepicker.util.JDatePickerUtil();
        sqlDateModel1 = new org.jdatepicker.impl.SqlDateModel();
        dateComponentFormatter6 = new org.jdatepicker.impl.DateComponentFormatter();
        dateChooserDialog1 = new datechooser.beans.DateChooserDialog();
        dateChooserDialog2 = new datechooser.beans.DateChooserDialog();
        dateChooserDialog3 = new datechooser.beans.DateChooserDialog();
        dateChooserDialog4 = new datechooser.beans.DateChooserDialog();
        jDatePickerUtil4 = new org.jdatepicker.util.JDatePickerUtil();
        jPanel1 = new javax.swing.JPanel();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        export = new javax.swing.JButton();
        pdf = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tanggal = new datechooser.beans.DateChooserCombo();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(null);

        back.setText("Home");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(270, 210, 150, 40);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("LAPORAN PENDAPATAN");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(230, 10, 270, 40);

        export.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Microsoft_Excel-01_25074.png"))); // NOI18N
        export.setText("Export excel");
        export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportActionPerformed(evt);
            }
        });
        jPanel1.add(export);
        export.setBounds(190, 160, 150, 40);

        pdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/PDF_24287.png"))); // NOI18N
        pdf.setText("Export PDF");
        pdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdfActionPerformed(evt);
            }
        });
        jPanel1.add(pdf);
        pdf.setBounds(350, 160, 150, 40);

        jLabel2.setText("Masukan Tanggal");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(190, 90, 120, 14);

        tanggal.setCalendarPreferredSize(new java.awt.Dimension(350, 250));
        tanggal.setLocale(new java.util.Locale("in", "ID", ""));
        tanggal.setBehavior(datechooser.model.multiple.MultyModelBehavior.SELECT_PERIOD);
        tanggal.setShowOneMonth(true);
        jPanel1.add(tanggal);
        tanggal.setBounds(190, 110, 300, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(778, 499));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
         this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void exportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportActionPerformed
        // TODO add your handling code here:
        
        if(tanggal.getText().equals("")){
            JOptionPane.showMessageDialog(null,"input tanggal");
        }else {
            try {
                /*Nama file excell*/
                File theDir = new File("C:/BackupFile/");
                if (!theDir.exists()){
                    theDir.mkdirs();
                }
                String filename = "C:/BackupFile/Laporan Pendapatan.xls" ;
                HSSFWorkbook workbook = new HSSFWorkbook();

                /*menentukan sheet*/
                HSSFSheet sheet = workbook.createSheet("Laporan Pendapatan");
                try {
                    String  sql = "select id_pesanan , tanggal ,nama_penerima ,nama_makanan , hrgmakanan , qty , total  "
                            + " from form_transaksi where tgl2= '"+ tanggal.getText() +"' and status = 'Sudah Sampai' " ;
                    String  sql2 = "select count(*) as jml  from form_transaksi"
                            + " where tgl2= '"+ tanggal.getText() +"' and status = 'Sudah Sampai' " ;

                    String  sql3 = "select sum(total) as pendapatan  from form_transaksi "
                            + "where tgl2= '"+ tanggal.getText() +"' and status = 'Sudah Sampai'" ;

                   // String sql2 = "Select count as total from form transaksi  where tanggal='"+ tanggal.getText() + "'" ;
                    int i =  1 ;
                    java.sql.Connection conn = (Connection)koneksi.configDB();
                    java.sql.Statement stm = conn.createStatement();
                    java.sql.ResultSet res = stm.executeQuery(sql);

                    java.sql.Statement stm2 = conn.createStatement();
                    java.sql.ResultSet res2 = stm2.executeQuery(sql2);

                    java.sql.Statement stm3 = conn.createStatement();
                    java.sql.ResultSet res3 = stm3.executeQuery(sql3);

                    res2.next();
                    res3.next();

                    if(res2.getString(1).equals("0")){
                         JOptionPane.showMessageDialog(null ,"tidak ada data");
                    }else {
                        HSSFRow rowhead = sheet.createRow((short)0);  /*index row 0*/
                        rowhead.createCell(0).setCellValue("ID Pesanan");  /*column 0*/
                        rowhead.createCell(1).setCellValue("Tanggal");  /*column 1*/
                        rowhead.createCell(2).setCellValue("Pemesan");  /*column 2*/
                        rowhead.createCell(3).setCellValue("Pesanan");  /*column 3*/
                        rowhead.createCell(4).setCellValue("Harga Makanan");  /*column 4*/
                        rowhead.createCell(5).setCellValue("QTY");  /*column 5*/
                        rowhead.createCell(6).setCellValue("Total");  /*column 6*/
                            while(res.next()){
                                HSSFRow row   = sheet.createRow((short)i);   /*index row 1*/
                                row.createCell(0).setCellValue(res.getString(1));  /*column 0*/
                                row.createCell(1).setCellValue(res.getString(2));  /* column  1*/
                                row.createCell(2).setCellValue(res.getString(3));  /* column 2*/
                                row.createCell(3).setCellValue(res.getString(4));  /* column 3*/
                                row.createCell(4).setCellValue(res.getString(5));  /* column 4*/
                                row.createCell(5).setCellValue(res.getString(6));  /* column 5*/
                                row.createCell(6).setCellValue(res.getString(7));  /* column 6*/
                                i++ ;
                            }
                                int a = Integer.parseInt(res2.getString(1));
                                HSSFRow rowFooter   = sheet.createRow((short) a + 1 );   /*index row 1*/
                                rowFooter.createCell(5).setCellValue("Total Pendapatan");  /* column 6*/
                                rowFooter.createCell(6).setCellValue(res3.getString(1));  /* column 6*/
                                FileOutputStream fileOut = new FileOutputStream(filename);
                                /*menulis file*/
                                workbook.write(fileOut);
                                /*menutup koneksi*/
                                fileOut.close();
                                JOptionPane.showMessageDialog(null, "Berhasil di export "  + filename);
                    }
                }catch(Exception e){
                    System.out.println(e);
                }
            } catch ( Exception ex ) {
                System.out.println(ex);
            }
        }
    }//GEN-LAST:event_exportActionPerformed

    private void pdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdfActionPerformed
        // TODO add your handling code here:
        if(tanggal.getText().equals("")){
            JOptionPane.showMessageDialog(null,"input tanggal");
        }else {
         try {
            File theDir = new File("C:/BackupFile/");
                if (!theDir.exists()){
                    theDir.mkdirs();
                }
            String  sql = "select id_pesanan , tanggal ,nama_penerima ,nama_makanan , hrgmakanan , qty , total  "
                            + " from form_transaksi where tgl2= '"+ tanggal.getText() +"' and status = 'Sudah Sampai' " ;
            String  sql2 = "select count(*) as jml  from form_transaksi"
                            + " where tgl2= '"+ tanggal.getText() +"' and status = 'Sudah Sampai' " ;
            String  sql3 = "select sum(total) as pendapatan  from form_transaksi "
                    + "where tgl2= '"+ tanggal.getText() +"' and status = 'Sudah Sampai'" ;
            java.sql.Connection conn = (Connection)koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);

            java.sql.Statement stm2 = conn.createStatement();
            java.sql.ResultSet res2 = stm2.executeQuery(sql2);

            java.sql.Statement stm3 = conn.createStatement();
            java.sql.ResultSet res3 = stm3.executeQuery(sql3);
            
            res2.next();
            res3.next(); 
                if(res2.getString(1).equals("0")){
                   JOptionPane.showMessageDialog(null,"data tidak ada");
                }else {
                /* Step-2: Initialize PDF documents - logical objects */
                    Document my_pdf_report = new Document();
                    String path = "C://BackupFile//Laporan Pendapatan.pdf" ;
                    PdfWriter.getInstance(my_pdf_report, new FileOutputStream(path));
                    my_pdf_report.open();            
                    my_pdf_report.add(new Paragraph("Laporan Pendapatan",FontFactory.getFont(FontFactory.TIMES_BOLD, 18, Font.BOLD, BaseColor.BLUE)));
                    my_pdf_report.add(new Paragraph(new Date().toString()));
                    my_pdf_report.add(new Paragraph("-------------------------------------------------------------------"
                            + "--------------------------------------------------------------"));
                    my_pdf_report.add(new Paragraph("\n"));
                    //we have four columns in our table
                    PdfPTable my_report_table = new PdfPTable(6);
                    //create a cell object
                    PdfPCell table_cell;
                    PdfPCell table_cell2;

                    my_report_table.addCell("Kode Pesanan");
                    my_report_table.addCell("Pemesan");
                    my_report_table.addCell("Pesanan");
                    my_report_table.addCell("QTY");
                    my_report_table.addCell("Harga Makanan");
                    my_report_table.addCell("Total");
                    my_report_table.setHeaderRows(1);

                    while (res.next()) {                
                        String id           = res.getString("id_pesanan");
                        table_cell          = new PdfPCell(new Phrase(id));
                        my_report_table.addCell(table_cell);

                        String penerima        = res.getString("nama_penerima");
                        table_cell          = new PdfPCell(new Phrase(penerima));
                        my_report_table.addCell(table_cell);

                        String nohp        = res.getString("nama_makanan");
                        table_cell          = new PdfPCell(new Phrase(nohp));
                        my_report_table.addCell(table_cell);

                        String alamat     = res.getString("qty");
                        table_cell          = new PdfPCell(new Phrase(alamat));
                        my_report_table.addCell(table_cell);

                        String makanan         = res.getString("hrgmakanan");
                        table_cell          = new PdfPCell(new Phrase(makanan));
                        my_report_table.addCell(table_cell);

                        String pengantar     = res.getString("total");
                        table_cell=new PdfPCell(new Phrase(pengantar));
                        my_report_table.addCell(table_cell);
                     }
                    /* Attach report table to PDF */
                    my_pdf_report.add(my_report_table);                       
                    my_pdf_report.close();

                    /* Close all DB related objects */
                    JOptionPane.showMessageDialog(null,"Disimpan " + path );
                }
            }catch(Exception e){

            }
        }
    }//GEN-LAST:event_pdfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaporanPendapatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaporanPendapatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaporanPendapatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaporanPendapatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LaporanPendapatan().setVisible(true);
            }
        });
    }
    
    public void loadPesanan(String data){
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private datechooser.beans.DateChooserDialog dateChooserDialog1;
    private datechooser.beans.DateChooserDialog dateChooserDialog2;
    private datechooser.beans.DateChooserDialog dateChooserDialog3;
    private datechooser.beans.DateChooserDialog dateChooserDialog4;
    private org.jdatepicker.impl.DateComponentFormatter dateComponentFormatter1;
    private org.jdatepicker.impl.DateComponentFormatter dateComponentFormatter2;
    private org.jdatepicker.impl.DateComponentFormatter dateComponentFormatter3;
    private org.jdatepicker.impl.DateComponentFormatter dateComponentFormatter4;
    private org.jdatepicker.impl.DateComponentFormatter dateComponentFormatter5;
    private org.jdatepicker.impl.DateComponentFormatter dateComponentFormatter6;
    private javax.swing.JButton export;
    private org.jdatepicker.JDateComponentFactory jDateComponentFactory1;
    private org.jdatepicker.JDateComponentFactory jDateComponentFactory2;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil1;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil2;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil3;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton pdf;
    private org.jdatepicker.impl.SqlDateModel sqlDateModel1;
    private datechooser.beans.DateChooserCombo tanggal;
    // End of variables declaration//GEN-END:variables

}
