/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pt_hokben;

import java.sql.Connection;
import javax.swing.JOptionPane;
import pt_hokben.Session ;
/**
 *
 * @author dasep
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        reset = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        regis = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel1.setText("Username");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(270, 50, 60, 13);

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        getContentPane().add(username);
        username.setBounds(350, 40, 180, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel2.setText("Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(270, 100, 70, 13);
        getContentPane().add(password);
        password.setBounds(350, 90, 180, 30);

        reset.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/delete.png"))); // NOI18N
        reset.setText("Cancel");
        getContentPane().add(reset);
        reset.setBounds(440, 130, 91, 30);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/login.png"))); // NOI18N
        jButton2.setText("Login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(350, 130, 90, 30);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel3.setText("Delivery System");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 70, 200, 31);

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel4.setText("PT Eka Bogainti");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 30, 210, 31);

        regis.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        regis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/register.png"))); // NOI18N
        regis.setText("Registrasi");
        regis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regisActionPerformed(evt);
            }
        });
        getContentPane().add(regis);
        regis.setBounds(350, 170, 180, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/delivery-guy.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 110, 80, 80);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/fgg.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 590, 230);

        setSize(new java.awt.Dimension(602, 263));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(username.getText().equals("")){
            JOptionPane.showMessageDialog(null,"isi username");
        }else if(password.getText().equals("")){
            JOptionPane.showMessageDialog(null,"isi password");
        }else {
            try {
                 String   sql = "Select * from user  where "
                            + "nama = '"+ username.getText()  +"' and password='"+ password.getText() +"' limit 1 "  ;                

                java.sql.Connection conn = (Connection)koneksi.configDB();
                java.sql.Statement stm = conn.createStatement();
                java.sql.ResultSet res = stm.executeQuery(sql);

                if(res.next()){
                   String level = res.getString("bagian");
                   if(level.equals("Admin") || level.equals("admin")){
                       Session.nama = res.getString("nama") ;
                        this.dispose();
                        Home a = new Home();
                        a.setVisible(true);                       
                   }else if (level.equals("Kasir") || level.equals("kasir")){
                       this.dispose();
                       aksitrans a = new aksitrans();
                       a.setVisible(true);
                   }else if(level.equals("User") || level.equals("user") ){
                       this.dispose();
                       Session.nama = res.getString("nama") ;
                       Session.nohp = res.getString("nohp") ;
                       daftar_menu a = new daftar_menu();
                       a.setVisible(true);
                   }
                }else {
                    JOptionPane.showMessageDialog(null,"akun tidak ditemukan");
                }
            }catch(Exception e){
                    JOptionPane.showMessageDialog(null,e.getMessage());
            }
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void regisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regisActionPerformed
        // TODO add your handling code here:
       form_register a = new form_register();
       a.setVisible(true);
    }//GEN-LAST:event_regisActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton regis;
    private javax.swing.JButton reset;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
