/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pt_hokben;

import java.sql.Connection;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dasep
 */
public class Master_biaya extends javax.swing.JFrame {

    /**
     * Creates new form Master_kendaraan
     */
    public Master_biaya() {
        initComponents();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        user = new javax.swing.JTable();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/plus.png"))); // NOI18N
        add.setText("Tambah");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add);
        add.setBounds(575, 202, 100, 30);

        user.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(user);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(23, 65, 652, 117);

        back.setText("Home");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(575, 240, 100, 26);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("MASTER BIAYA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(300, 12, 138, 17);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 700, 370);

        setSize(new java.awt.Dimension(704, 392));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Biaya_kirim a = new Biaya_kirim();
        a.setVisible(true);
    }//GEN-LAST:event_addActionPerformed

    private void userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        int baris            = user.rowAtPoint(evt.getPoint());
        String id            = user.getValueAt(baris,0).toString();
        String jarak         = user.getValueAt(baris,1).toString();
        String biaya         =  user.getValueAt(baris,2).toString();
        String keterangan    = user.getValueAt(baris,3).toString();
        
        String[]  data = { id , jarak , biaya , keterangan } ;
        this.dispose();
        
        FormEditBiaya a = new FormEditBiaya();
        a.form(data);
        a.setVisible(true);
    }//GEN-LAST:event_userMouseClicked

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.dispose();      
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void loadData(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Biaya");
        model.addColumn("Jarak");
        model.addColumn("Biaya");
        model.addColumn("Keterangan");
        
        //tampilkan data makanan kedalam table 
        try {
            String sql = "Select * from form_biayakirim  " ;
            java.sql.Connection conn = (Connection)koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[] {res.getString(1) ,  res.getString(2) , res.getString(3) , res.getString(4)
               } );
            }
            user.setModel(model);
        }catch(Exception e){
            
        } 
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Master_biaya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Master_biaya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Master_biaya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Master_biaya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Master_biaya().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable user;
    // End of variables declaration//GEN-END:variables
}
