/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pt_hokben;

import java.io.File;
import java.io.FileOutputStream;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;

/**
 *
 * @author dasep
 */
public class Master_utilitas extends javax.swing.JFrame {

    /**
     * Creates new form Master_kendaraan
     */
    private String id ; 
    public Master_utilitas() {
        initComponents();
        loadData(this.id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        utilitas = new javax.swing.JTable();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        key = new javax.swing.JTextField();
        reset1 = new javax.swing.JButton();
        cari2 = new javax.swing.JButton();
        export = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/plus.png"))); // NOI18N
        add.setText("Tambah");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add);
        add.setBounds(620, 250, 100, 40);

        utilitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        utilitas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                utilitasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(utilitas);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 107, 662, 127);

        back.setText("Home");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(620, 300, 100, 40);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Laporan Pengeluaran");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(270, 30, 240, 22);
        getContentPane().add(key);
        key.setBounds(60, 250, 131, 40);

        reset1.setText("Reset Pencarian");
        reset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset1ActionPerformed(evt);
            }
        });
        getContentPane().add(reset1);
        reset1.setBounds(270, 250, 124, 40);

        cari2.setText("Cari ");
        cari2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari2ActionPerformed(evt);
            }
        });
        getContentPane().add(cari2);
        cari2.setBounds(200, 250, 56, 40);

        export.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Microsoft_Excel-01_25074.png"))); // NOI18N
        export.setText("Export Excel");
        export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportActionPerformed(evt);
            }
        });
        getContentPane().add(export);
        export.setBounds(450, 250, 150, 40);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 760, 430);

        setSize(new java.awt.Dimension(768, 454));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        this.dispose();
        utilitas a = new utilitas();
        a.setVisible(true);
    }//GEN-LAST:event_addActionPerformed

    private void utilitasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_utilitasMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        int baris            = utilitas.rowAtPoint(evt.getPoint());
        String id            = utilitas.getValueAt(baris,0).toString();
        String merk          = utilitas.getValueAt(baris,1).toString();
        String bahanbakar    =  utilitas.getValueAt(baris,2).toString();
        String biaya         =  utilitas.getValueAt(baris,3).toString();
        String keterangan    = utilitas.getValueAt(baris,4).toString();
        
        String[]  data = { id , merk , bahanbakar , biaya , keterangan } ;
        this.dispose();
        
        FormEditUtilitas a = new FormEditUtilitas();
        a.form(data);
        a.setVisible(true);
    }//GEN-LAST:event_utilitasMouseClicked

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_backActionPerformed

    private void reset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset1ActionPerformed
        // TODO add your handling code here:
        String data = null ;
        loadData(data);
    }//GEN-LAST:event_reset1ActionPerformed

    private void cari2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari2ActionPerformed
        // TODO add your handling code here:
        if(key.getText().equals("")){
            JOptionPane.showMessageDialog(null,"keyword kosong");
        }else {
            String data = key.getText();
            loadData(data);
        }
    }//GEN-LAST:event_cari2ActionPerformed

    private void exportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportActionPerformed
        // TODO add your handling code here:
        try {
                File theDir = new File("C:/BackupFile/");
                if (!theDir.exists()){
                    theDir.mkdirs();
                }
            /*Nama file excell*/
            String filename = "C:/BackupFile/Laporan Pengeluaran.xls" ;
            HSSFWorkbook workbook = new HSSFWorkbook();

            /*menentukan sheet*/
            HSSFSheet sheet = workbook.createSheet("FirstSheet");
            try {
                String  sql = "select * from form_utilitas " ;
                int i =  1 ;
                java.sql.Connection conn = (Connection)koneksi.configDB();
                java.sql.Statement stm = conn.createStatement();
                java.sql.ResultSet res = stm.executeQuery(sql);
                HSSFRow rowhead = sheet.createRow((short)0);  /*index row 0*/
                rowhead.createCell(0).setCellValue("No");  /*column 0*/
                rowhead.createCell(1).setCellValue("Merek Kendaraan");  /*column 1*/
                rowhead.createCell(2).setCellValue("Bahan Bakar");  /*column 2*/
                rowhead.createCell(3).setCellValue("Biaya Operasional");  /*column 2*/
                rowhead.createCell(4).setCellValue("Tanggal");  /*column 2*/
                rowhead.createCell(5).setCellValue("Keterangan");  /*column 2*/
                while(res.next()){
                    HSSFRow row   = sheet.createRow((short)i);   /*index row 1*/
                    row.createCell(0).setCellValue(i);  /*column 0*/
                    row.createCell(1).setCellValue(res.getString(2));  /* column  1*/
                    row.createCell(2).setCellValue(res.getString(3));  /* column 2*/
                    row.createCell(3).setCellValue(res.getString(4));  /* column 2*/
                    row.createCell(4).setCellValue(res.getString(5));  /* column 2*/
                    row.createCell(5).setCellValue(res.getString(6));  /* column 2*/
                    i++ ;
                }
            }catch(Exception e){

            }
            FileOutputStream fileOut = new FileOutputStream(filename);

            /*menulis file*/
            workbook.write(fileOut);

            /*menutup koneksi*/
            fileOut.close();
            JOptionPane.showMessageDialog(null, "Berhasil di export " + filename);
        } catch ( Exception ex ) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_exportActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void loadData(String data){
       DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Utilitas");
        model.addColumn("Merk Kendaraan");
        model.addColumn("Bahan Bakar");
        model.addColumn("Biaya Operasional");
        model.addColumn("Keterangan");
        model.addColumn("Tanggal");
        
        //tampilkan data makanan kedalam table 
        try {
            String sql = "" ;

            if(data == null ){
                sql = "Select * from form_utilitas  " ;
            }else {
                sql = "Select * from form_utilitas where "
                        + "tanggal like  '%"+ data +"%' or merk_kendaraan like '%"+ data +"%'   "  ;                
            }
            
            java.sql.Connection conn = (Connection)koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[] {res.getString(1) ,  res.getString(2) , res.getString(3) , res.getString(4)
                         , res.getString(6) , res.getString(5)
               } );
            }
            utilitas.setModel(model);
        }catch(Exception e){
            
        } 
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Master_utilitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Master_utilitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Master_utilitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Master_utilitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Master_utilitas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton back;
    private javax.swing.JButton cari2;
    private javax.swing.JButton export;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField key;
    private javax.swing.JButton reset1;
    private javax.swing.JTable utilitas;
    // End of variables declaration//GEN-END:variables
}
