/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pt_hokben;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;

/**
 *
 * @author dasep
 */
public class Master_kendaraan extends javax.swing.JFrame {

    /**
     * Creates new form Master_kendaraan
     */
    private String id ;
    public Master_kendaraan() {
        initComponents();
        loadData(this.id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        kendaraan = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        key = new javax.swing.JTextField();
        cari2 = new javax.swing.JButton();
        reset1 = new javax.swing.JButton();
        export = new javax.swing.JButton();
        pdf = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/plus.png"))); // NOI18N
        jButton2.setText("Tambah");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(610, 220, 100, 40);

        kendaraan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        kendaraan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kendaraanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(kendaraan);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 94, 652, 120);

        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(610, 270, 100, 40);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("MASTER KENDARAAN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(300, 30, 240, 28);

        key.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keyActionPerformed(evt);
            }
        });
        getContentPane().add(key);
        key.setBounds(60, 220, 131, 40);

        cari2.setText("Cari ");
        cari2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari2ActionPerformed(evt);
            }
        });
        getContentPane().add(cari2);
        cari2.setBounds(210, 220, 55, 40);

        reset1.setText("Reset Pencarian");
        reset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset1ActionPerformed(evt);
            }
        });
        getContentPane().add(reset1);
        reset1.setBounds(280, 220, 111, 40);

        export.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Microsoft_Excel-01_25074.png"))); // NOI18N
        export.setText("Export Excel");
        export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportActionPerformed(evt);
            }
        });
        getContentPane().add(export);
        export.setBounds(440, 220, 150, 40);

        pdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/PDF_24287.png"))); // NOI18N
        pdf.setText("Export PDF");
        pdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdfActionPerformed(evt);
            }
        });
        getContentPane().add(pdf);
        pdf.setBounds(440, 270, 150, 40);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 750, 400);

        setSize(new java.awt.Dimension(754, 422));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        input_master_kendaraan a = new input_master_kendaraan();
        a.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void kendaraanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kendaraanMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        int baris           = kendaraan.rowAtPoint(evt.getPoint());
        String kode         = kendaraan.getValueAt(baris,0).toString();
        String merk         = kendaraan.getValueAt(baris,1).toString();
        String jenis        = kendaraan.getValueAt(baris,2).toString();
        String nopolisi     = kendaraan.getValueAt(baris,3).toString();
        String masa         = kendaraan.getValueAt(baris,4).toString();
        String kondisi      = kendaraan.getValueAt(baris,5).toString();
        
        String[]  data = { kode , merk , jenis , nopolisi , masa ,kondisi  } ;
        this.dispose();
        
        FormEditKendaraan a = new FormEditKendaraan();
        a.form(data);
        a.setVisible(true);
    }//GEN-LAST:event_kendaraanMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void exportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportActionPerformed
        // TODO add your handling code here:
        try {

        /*Nama file excell*/
            String filename = "C:/ReportKendaraan.xls" ;
            HSSFWorkbook workbook = new HSSFWorkbook();

        /*menentukan sheet*/
            HSSFSheet sheet = workbook.createSheet("FirstSheet"); 
            try {
           String  sql = "select * from master_kendaraan " ;
            int i =  1 ; 
            java.sql.Connection conn = (Connection)koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            HSSFRow rowhead = sheet.createRow((short)0);  /*index row 0*/
                 rowhead.createCell(0).setCellValue("No");  /*column 0*/
                 rowhead.createCell(1).setCellValue("Kode Kendaraan");  /*column 1*/
                 rowhead.createCell(2).setCellValue("Merek Kendaraan");  /*column 1*/
                 rowhead.createCell(3).setCellValue("Jenis Kendaraaan");  /*column 2*/
                 rowhead.createCell(4).setCellValue("No Polisi");  /*column 2*/
                 rowhead.createCell(5).setCellValue("Masa Kendaraaan");  /*column 2*/
                 rowhead.createCell(6).setCellValue("Kondisi Kendaraaan");  /*column 2*/
            while(res.next()){
                    HSSFRow row   = sheet.createRow((short)i);   /*index row 1*/
                    row.createCell(0).setCellValue(i);  /*column 0*/
                    row.createCell(1).setCellValue(res.getString(1));  /* column  1*/
                    row.createCell(2).setCellValue(res.getString(2));  /* column  1*/
                    row.createCell(3).setCellValue(res.getString(3));  /* column 2*/
                    row.createCell(4).setCellValue(res.getString(4));  /* column 2*/
                    row.createCell(5).setCellValue(res.getString(5));  /* column 2*/
                    row.createCell(6).setCellValue(res.getString(6));  /* column 2*/
                i++ ;
            }
        }catch(Exception e){
            
        }
            FileOutputStream fileOut = new FileOutputStream(filename);

            /*menulis file*/
            workbook.write(fileOut);

           /*menutup koneksi*/
            fileOut.close();
               JOptionPane.showMessageDialog(null, "Berhasil di export di C:/ReportKendaraan.xls");
        } catch ( Exception ex ) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_exportActionPerformed

    private void pdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdfActionPerformed
        // TODO add your handling code here:
        try {
            String path = "D://KendaraanReport.pdf" ;
            String  sql = "select * from master_kendaraan " ;
            java.sql.Connection conn = (Connection)koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            /* Step-2: Initialize PDF documents - logical objects */
        Document my_pdf_report = new Document();
        PdfWriter.getInstance(my_pdf_report, new FileOutputStream(path));
        my_pdf_report.open();            
        my_pdf_report.add(new Paragraph("Laporan Master Kendaraan",FontFactory.getFont(FontFactory.TIMES_BOLD, 18, Font.BOLD, BaseColor.BLUE)));
        my_pdf_report.add(new Paragraph(new Date().toString()));
        my_pdf_report.add(new Paragraph("-------------------------------------------------------------------"
                + "--------------------------------------------------------------"));
        my_pdf_report.add(new Paragraph("\n"));
        //we have four columns in our table
        PdfPTable my_report_table = new PdfPTable(6);
        //create a cell object
        PdfPCell table_cell;
        PdfPCell table_cell2;
        
        
        table_cell2=new PdfPCell(new Phrase("Kode Kendaraan"));
        table_cell2.setBackgroundColor(BaseColor.CYAN);
        my_report_table.addCell(table_cell2);
        table_cell2=new PdfPCell(new Phrase("Merek"));
        table_cell2.setBackgroundColor(BaseColor.CYAN);
        my_report_table.addCell(table_cell2);
        table_cell2=new PdfPCell(new Phrase("Jenis"));
        table_cell2.setBackgroundColor(BaseColor.CYAN);
        my_report_table.addCell(table_cell2);
        table_cell2=new PdfPCell(new Phrase("No Polisi"));
        table_cell2.setBackgroundColor(BaseColor.CYAN);
        my_report_table.addCell(table_cell2);
        table_cell2=new PdfPCell(new Phrase("Masa"));
        table_cell2.setBackgroundColor(BaseColor.CYAN);
        my_report_table.addCell(table_cell2);
        table_cell2=new PdfPCell(new Phrase("Kondisi"));
        table_cell2.setBackgroundColor(BaseColor.CYAN);
        my_report_table.addCell(table_cell2);

        
        while (res.next()) {                
            String kode         = res.getString("kode_kendaraan");
            table_cell          = new PdfPCell(new Phrase(kode));
            my_report_table.addCell(table_cell);
            
            String merk         = res.getString("merk_kendaraan");
            table_cell          = new PdfPCell(new Phrase(merk));
            my_report_table.addCell(table_cell);
            
            String jenis        = res.getString("jenis_kendaraan");
            table_cell          = new PdfPCell(new Phrase(jenis));
            my_report_table.addCell(table_cell);
            
            String nopolisi     = res.getString("no_polisi");
            table_cell          = new PdfPCell(new Phrase(nopolisi));
            my_report_table.addCell(table_cell);
            
            String masa         = res.getString("masa_kendaraan");
            table_cell          = new PdfPCell(new Phrase(masa));
            my_report_table.addCell(table_cell);
            
            String kondisi      = res.getString("kondisi_kendaraan");
            table_cell=new PdfPCell(new Phrase(kondisi));
            my_report_table.addCell(table_cell);
            
         }
        /* Attach report table to PDF */
        my_pdf_report.add(my_report_table);                       
        my_pdf_report.close();

        /* Close all DB related objects */
        JOptionPane.showMessageDialog(null,"Disimpan " + path );
        }catch(Exception e){
            
        }
        
    }//GEN-LAST:event_pdfActionPerformed

    private void reset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset1ActionPerformed
        // TODO add your handling code here:
        String data = null ;
        loadData(data);
    }//GEN-LAST:event_reset1ActionPerformed

    private void cari2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari2ActionPerformed
        // TODO add your handling code here:
        if(key.getText().equals("")){
            JOptionPane.showMessageDialog(null,"keyword kosong");
        }else {
            String data = key.getText();
            loadData(data);
        }
    }//GEN-LAST:event_cari2ActionPerformed

    private void keyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keyActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void loadData(String data){
       DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Kode Kendaraan");
        model.addColumn("Merk Kendaraan");
        model.addColumn("Jenis Kendaraan");
        model.addColumn("No Polisi");
        model.addColumn("Masa Kendaraan");
        model.addColumn("Kondisi Kendaraan");
        
        //tampilkan data makanan kedalam table 
        try {
            String sql = "" ;

            if(data == null ){
                sql = "Select * from master_kendaraan   " ;
            }else {
                sql = "Select * from master_kendaraan where "
                        + "kode_kendaraan like  '%"+ data +"%' or merk_kendaraan like '%"+ data +"%'  "
                        + "or kondisi_kendaraan like '%"+ data +"%'   "  ;                
            }
            
            java.sql.Connection conn = (Connection)koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[] {res.getString(1) ,  res.getString(2) , res.getString(3) , res.getString(4)
                , res.getString(5) , res.getString(6) } );
            }
            kendaraan.setModel(model);
        }catch(Exception e){
            
        } 
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Master_kendaraan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Master_kendaraan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Master_kendaraan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Master_kendaraan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Master_kendaraan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cari2;
    private javax.swing.JButton export;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable kendaraan;
    private javax.swing.JTextField key;
    private javax.swing.JButton pdf;
    private javax.swing.JButton reset1;
    // End of variables declaration//GEN-END:variables
}
