package pt_hokben;



import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import pt_hokben.koneksi;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Adm-004
 */
public class utilitas extends javax.swing.JFrame {

    /**
     * Creates new form utilitas
     */
    public utilitas() {
        initComponents();
        listKendaraan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        listKendaraan = new javax.swing.JComboBox<>();
        bahanbakar = new javax.swing.JTextField();
        biaya = new javax.swing.JTextField();
        keterangan = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Input Utyliti");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(170, 10, 76, 17);

        jLabel3.setText("Merk Kendaraan");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 90, 94, 16);

        jLabel4.setText("Bahan Bakar");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 130, 73, 16);

        jLabel5.setText("Biaya Operasional");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 170, 103, 16);

        jLabel6.setText("Keterangan");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 210, 66, 16);

        listKendaraan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Kendaraan" }));
        jPanel1.add(listKendaraan);
        listKendaraan.setBounds(160, 80, 179, 26);
        jPanel1.add(bahanbakar);
        bahanbakar.setBounds(160, 130, 179, 30);
        jPanel1.add(biaya);
        biaya.setBounds(160, 170, 179, 30);
        jPanel1.add(keterangan);
        keterangan.setBounds(160, 210, 179, 30);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/diskette.png"))); // NOI18N
        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(160, 250, 93, 30);

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/previous.png"))); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(260, 250, 80, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/fgg.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 540, 650);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 408, 450);

        setSize(new java.awt.Dimension(416, 483));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Master_utilitas a  = new Master_utilitas();
        a.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void reset(){
        listKendaraan.setSelectedItem("Pilih Kendaraan");
        bahanbakar.setText("");
        biaya.setText("");
        keterangan.setText("");
    }
    
    private  String getTanggal() {  
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");  
        Date date = new Date();  
        return dateFormat.format(date);  
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       utilitas tgl = new utilitas();
        
        String tanggal   = tgl.getTanggal() ;
        if(listKendaraan.getSelectedItem().equals("") || bahanbakar.getText().equals("")|| biaya.getText().equals("") 
                || keterangan.getText().equals("")){
            JOptionPane.showMessageDialog(null,"field kosong");
        }else {
            try {
                String sql = "INSERT INTO form_utilitas ("
                        + " merk_kendaraan , bahan_bakar , biaya_operasional , tanggal , keterangan ) values "
                        + "('"+ listKendaraan.getSelectedItem() +"' , '"+ bahanbakar.getText() +"' ,"
                        + " '"+ biaya.getText() +"' , "
                        + " '"+ tanggal +"' ,"
                        + " '"+ keterangan.getText() +"' ) " ;
                  java.sql.Connection conn = (Connection)koneksi.configDB();
                  java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                  pst.execute();
                  JOptionPane.showMessageDialog(null,"Penyimpanan Berhasil");
                  reset();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void listKendaraan(){

        try {
            String sql  = "SELECT * FROM master_kendaraan ";
            java.sql.Connection conn = (Connection)koneksi.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery(sql);
            
            while (rs.next()) {                
                listKendaraan.addItem(rs.getString("merk_kendaraan"));
            }
        
           
        } catch (SQLException e) {
            
        }
        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(utilitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(utilitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(utilitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(utilitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new utilitas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTextField bahanbakar;
    private javax.swing.JTextField biaya;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField keterangan;
    private javax.swing.JComboBox<String> listKendaraan;
    // End of variables declaration//GEN-END:variables
}
